" line numbers
set ruler
syntax on
filetype indent plugin on
set nohlsearch

" python tabs
set tabstop=4
set expandtab
set shiftwidth=2
set softtabstop=2

" yy, d and p works with clipboard
set clipboard=unnamed
set backspace=eol,start,indent
